on: [push]

name: CI

concurrency:
  group: ${{ github.ref_name }}
  cancel-in-progress: true # ${{ github.ref != format('refs/heads/{0}', github.event.repository.default_branch) }}

jobs:
  build_and_test:
    name: build and test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Build
        run: cargo build --release --all-features

      - name: Tests
        run: cargo test
